### ISSUE TITLE
Traduccion

### ISSUE THREAD

**Issue by Dracoibz** [tralph3/CrossCode-Esp#1]
En la cadena 52 de [arid-dng] Vermillion Dungeon/Tower, 
data/maps/arid-dng/first/outside.json entities/86/settings/event/204/message #865
EventTrigger MuchDramaScene START IF party.has.Schneider2
SHOW_MSG antagonists.designer @BROKEN
No! Not YOU again!!
Tiene más sentido (a mi pareder):
¡No! ¡¡TÚ otra vez no!!

**Comment by Dracoibz** [comment]
En la cadena 125 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/first/room-04.json entities/24/settings/event/20/message #10
EventTrigger start
SHOW_MSG main.sergey @SERIOUS
As strange as it sounds, it is our best chance to get out of this place.
Aunque suene raro, es nuestra mejor oportunidad para salir de este lugar.

**Comment by Dracoibz** [comment]
En la cadena 144 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/first/room-06.json entities/44/settings/interact/event/9/thenStep/10/message #28
Prop exitSign SPAWN IF map.exitSign
IF plot.line == 13950
SHOW_MSG main.sergey @ROLL_EYES
Sorry, I forgot to fix the routine for sideway jumps...
habria que cambiar "de lado" por laterales
(está bien de las dos maneras, pero me suena mejor lateral)

**Comment by Dracoibz** [comment]
En la cadena 199 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/first/room-10.json entities/31/settings/event/33/message #872
EventTrigger bossStart START IF tmp.bossStart
SHOW_MSG antagonists.designer @SMILE
It is quite entertaining to say the least!
¡Debo admitir que es bastante entretenido!

**Comment by Dracoibz** [comment]
En la cadena 354 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/second/f99/boss-1.json entities/92/settings/event/0/thenStep/0/message #52
EventTrigger roundTalk START IF tmp.designer.talkStart > tmp.designer.talkEnd
IF tmp.designer.talkStart == 2
SHOW_SIDE_MSG antagonists.designer @LAUGH
You do not disappoint!
Hay un error ortográfico:  decepcionas -----> decepcionas

**Comment by Dracoibz** [comment]
En la cadena 356 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/second/f99/boss-1.json entities/92/settings/event/2/thenStep/0/message #58
EventTrigger roundTalk START IF tmp.designer.talkStart > tmp.designer.talkEnd
IF tmp.designer.talkStart >= 4 && tmp.designer.talkStart < 8
SHOW_SIDE_MSG antagonists.designer @SMILE
...you prevailed!
Seria: ¡...tu prevaleciste!

**Comment by Dracoibz** [comment]
En la cadena 365 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/second/f99/boss-1.json entities/97/settings/event/6/message #79
EventTrigger End START IF tmp.nextStage
SHOW_SIDE_MSG antagonists.designer @SMILE
High into the sky, we shall rise!!
¡¡Alto en el cielo, ascenderemos!!
(creo que va más de ascender como concepto, que de subir)

**Comment by Dracoibz** [comment]
en la cadena 371 de [arid-dng] Vermillion Dungeon/Tower,
data/maps/arid-dng/second/f99/boss-2.json entities/178/settings/event/4/text #1
EventTrigger firstHpCharge START IF tmp.hpCharge.start
SHOW_DREAM_MSG
The time has come to rise further beyond!
¡Ha llegado el momento de ascender más allá!
(queda muy raro eso de alcanzar aún más lejos)

**Comment by tralph3** [comment]
Si, debo admitir que muchas frases suenan raras, pero es normal. Cuando traduzco voy  con cierta velocidad. Paro a considerar algunas cosas, pero muchas veces pongo la primera traduccion que se me viene a la cabeza. Una vez termine con eso, lo reviso para arreglar cosas, eso mismo hice con la primera parte del juego que saque como demostración. También tenía frases raras por falta de contexto u otro motivo que fui arreglando mientras jugaba. Le di 3 o 4 pasadas antes de que quede como me gusta. Ademas, Vermillion es de las primeras zonas que hice. Pero bueno, gracias por las sugerencias, voy  revisarlas.
