### ISSUE TITLE
Translate the online/offline/party status labels of party members in the Social menu

### ISSUE THREAD

**Issue by dmitmel** [tralph3/CrossCode-Esp#14]
![image](https://user-images.githubusercontent.com/15367354/149674065-33a5db6d-466a-4af1-9569-842d1e2d783f.png)

**Comment by tralph3** [comment]
I take it these are now strings that get translated in weblate, right? Well, can we use images instead? To make the translations fit I had to reduce the width of the E character by 1 pixel, it doesn't fit otherwise. As you can see here:

<img src="https://i.imgur.com/p770cAn.png"></img>

**Comment by dmitmel** [comment]
Don't worry, I made the colorful backgrounds automatically extend to fit the text.

**Comment by tralph3** [comment]
Ah, great, no problems then, thanks.
