### ISSUE TITLE
Translate combat rank label

### ISSUE THREAD

**Issue by tralph3** [tralph3/CrossCode-Esp#16]
<img src="https://media.discordapp.net/attachments/796190306415542312/932422405031342120/unknown.png"></img>

**Comment by dmitmel** [comment]
Is this good enough? I believe that expanding the whole UI would be really tough.

![image](https://user-images.githubusercontent.com/15367354/151885087-f0e9c4a8-e8bd-490a-9bd8-53f32722f78a.png)

**Comment by tralph3** [comment]
That' perfect dima, thanks.

**Comment by dmitmel** [comment]
I haven't actually fixed it yet! :slightly_smiling_face:
