### ISSUE TITLE
Error de texto en las misiones de las facciones

### ISSUE THREAD

**Issue by Pandanube** [tralph3/CrossCode-Esp#2]
No tengo idea de como reportar un error pero en la imagen se ve, perdón si no sigo las "reglas de reporte" o si hay algo asi establecido
![image](https://user-images.githubusercontent.com/32661604/129422416-cba83f3e-0ccc-476a-818a-bd468dd16a57.png)

**Comment by tralph3** [comment]
Muchas gracias. Creo que eso ya esta arreglado en la ultima version, que no salio todavia.

**Comment by Pandanube** [comment]
> Muchas gracias. Creo que eso ya esta arreglado en la ultima version, que no salio todavia.
UwU lo espero con ansias, gracias por todo su trabajo <3
