### ISSUE TITLE
Change elevator labels in Temple Mine (or in general)

### ISSUE THREAD

**Issue by tralph3** [tralph3/CrossCode-Esp#22]
![image](https://user-images.githubusercontent.com/41462117/185771726-d62600e4-4911-453d-9144-8db8e951fdfc.png)

Labels should be:

...
F2 -> P2
F1 -> P1
G -> PB
B1 -> S1
B2 -> S2
...

**Comment by dmitmel** [comment]
Is this good enough?
![image](https://user-images.githubusercontent.com/15367354/209130008-7138194a-1bb7-40ae-9603-98454063d878.png)

**Comment by tralph3** [comment]
Yes, that's perfect dima. Thanks.
