### ISSUE TITLE
Change CP to PC in Circuit Menu

### ISSUE THREAD

**Issue by tralph3** [tralph3/CrossCode-Esp#23]
![image](https://user-images.githubusercontent.com/41462117/206827555-0e284e29-2ca2-4345-82da-be265c5addb6.png)

**Comment by tralph3** [comment]
Btw, dima, how can I integrate these changes into the spanish mod? I don't have that repo cloned anywhere.

**Comment by dmitmel** [comment]
It's in the dependency library, when we make a release I will also make a release of that. And I have already switched CP to PC on Weblate.
