### ISSUE TITLE
Some quest names overflow the quest info box

### ISSUE THREAD

**Issue by dmitmel** [tralph3/CrossCode-Esp#24]
![Screenshot_2022-12-10_21-27-14](https://user-images.githubusercontent.com/15367354/206874095-f3f22c2f-2380-4960-b4d7-0dbf13c6afde.png)

**Comment by tralph3** [comment]
We'll try to shorten them, shouldn't be *too* difficult. Seems that ~35 characters is the max.

**Comment by dmitmel** [comment]
There's no need, I'm inserting a scrolling label here

**Comment by tralph3** [comment]
Well, that'd be fine as a fallback, but I'd still prefer to try and not rely on that. Still, thank you anyway.

**Comment by dmitmel** [comment]
Here's a snippet to make the quests menu display all quests (doesn't actually unlock everything):

```js
sc.QuestModel.inject({
  getQuestList(type, sort) {
    let list = Object.values(this.staticQuests);
    if (sort != null) this.sortQuestList(list, sort);
    return list;
  },
});
```

**Comment by tralph3** [comment]
Oh, that'd be really useful. Thanks!
