### ISSUE TITLE
Change LVL to NVL on top left of inventory screen

### ISSUE THREAD

**Issue by tralph3** [tralph3/CrossCode-Esp#25]
![image](https://user-images.githubusercontent.com/41462117/206929787-ab4c1952-6ad4-4da4-84b1-0ef793e58753.png)

**Comment by tralph3** [comment]
Actually I didn't even realize that HP and SP are also there :P 

Those should be PV and PE respectively, as in the character screen.

**Comment by dmitmel** [comment]
Please find all other GUIs where the labels "HP", "SP", "LVL", "EXP" and such appear. They always end up being hardcoded, so I might as well add the code for pulling all of those strings from the localization files in a single commit.

**Comment by tralph3** [comment]
They also appear here in the group screen:

![image](https://user-images.githubusercontent.com/41462117/207157568-b32a8995-2883-4115-b176-446b4ff88b49.png)

Here in the status screen:

![image](https://user-images.githubusercontent.com/41462117/207157670-16cc8d31-3e8d-46f4-94a5-dccae45d3433.png)

In the equipment screen:

![image](https://user-images.githubusercontent.com/41462117/207157745-3ee6581f-d77d-41b0-87e6-04ec28c42011.png)

Maybe this is a bit too much, but it technically also appears in the item icons:

![image](https://user-images.githubusercontent.com/41462117/207157881-2614a1aa-3137-44b4-8bbb-23241e8e8ea5.png)

As you may guess, in spanish that'd be N

Although already translated, it also appears in the mission screen, don't know if that's translatable via text yet:

![image](https://user-images.githubusercontent.com/41462117/207158572-07b3abc2-b69b-488d-91bd-104e7d3a60d6.png)

And of course, in the top left in game, and on enemies:

![image](https://user-images.githubusercontent.com/41462117/207158655-0daad7f8-dfbe-421b-95cc-f97610fcc2da.png)

I think that's everything.

**Comment by tralph3** [comment]
Oh, btw, found another one. There's the "LVL" thingy on the right side:

![image](https://user-images.githubusercontent.com/41462117/209008892-522a4693-df99-4493-95e5-7d0a6536ad7d.png)
